title: Roblox Script Assistance - Resources
invite_link: https://discord.com/invite/pHhuTHUPbm
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
plugins:
  - jekyll-autoprefixer
