title: Roblox Development Assistance - Resources
invite_link: https://discord.com/invite/pHhuTHUPbm
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
plugins:
  - jekyll-archives
  - jekyll-autoprefixer

jekyll-archives:
  enabled:
    - year
    - month
    - categories
  layouts:
    year: archive-year
    month: archive-month
    category: archive-category
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"
    category: "/category/:name/"