name: Build and deploy to Github Pages

on: ["push"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Build static files
        run: |
          bundle exec jekyll build
      - name: Tar static files
        if: success() && github.ref == 'refs/heads/master'
        run: tar -zcvf sources.tar.gz pages/build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        if: success() && github.ref == 'refs/heads/master'
        with:
          name: Static files
          path: pages/build/
          if-no-files-found: error
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run tests
        run: |
          bundle exec rake test
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    needs: [build, test]
    if: success() && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download static files
        uses: actions/download-artifact@v3
        with:
          name: Static files
          path: build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: build